name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches: main 
  workflow_dispatch:        # manual “Run workflow” button
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - content/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
     # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "my_book/my_book/_build/html"

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
